server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://web-study.ctumsyopmesy.ap-northeast-2.rds.amazonaws.com:3306/project_winiaaid?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: admin
    password: 1q2w3e4r
  servlet:
    multipart:
      max-file-size: 50MB        
      max-request-size: 50MB
  jpa:
    hibernate:
     ddl-auto:  update
     naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

        
   
mybatis:
  mapper-locations:
  - /mappers/*.xml
  
file:
  path: C:/project/workspace/git/winiaaid-TeamProject/upload/
#  path: /Users/gim-yujeong/workspace/git/winiaaid-TeamProject/upload/