server:
  port: ${port:8000}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 50MB        
      max-request-size: 50MB

  profiles:
    include: private

mybatis:
  mapper-locations:
  - /mappers/*.xml
  
file:
  path: /home/ubuntu/springboot/project/winiaaid-TeamProject/upload/
#  path: C:/project/workspace/git/winiaaid-TeamProject/src/main/resources/static/
#  path: /Users/gim-yujeong/workspace/git/winiaaid-TeamProject/upload/




# log4jdbc, Mybatis Console Log
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: OFF     #SQL만 로그로 남긴다.
      sqltiming: INFO    #SQL과 소요시간을 표기한다.
      connection : OFF  # 커넥션 확인가능
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        web: DEBUG
      com:
        zaxxer:
          hikari:
            HikariDataSource: ERROR




